name: friends_khata
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  form_field_validator: ^1.1.0
  flutter_signin_button: ^2.0.0
  flash: ^2.0.3+2
  cupertino_icons: ^1.0.4
  google_fonts: ^2.3.1
  freezed_annotation: ^1.1.0
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  google_sign_in: ^5.2.4
  dartz: ^0.10.1
  flutter_riverpod: ^1.0.3
  auto_route: ^3.2.3
  cloud_firestore: ^3.1.11
  toggle_switch: ^1.4.0
  font_awesome_flutter: ^9.2.0
  data_table_2: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  build_runner: ^2.1.8
  auto_route_generator: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/
